### ISSUE TITLE
setUpAll and tearDownAll

### ISSUE THREAD

**Issue by tylersnavely-wf** [dart-lang/unittest#33] opened 2015-03-09 20:48 UTC
See: https://github.com/dart-lang/unittest/issues/17#issuecomment-75301142

Testers may want that higher level setUp and tearDown that only execute before the first test, and after the final test.

Example:
Someone may want a robust test suite that starts a selenium server only at the beginning of the suite if one is not already running, and then kill the server after all tests have completed.

**Comment by nex3** [comment] 2015-03-09 20:50
Duplicate of #18

**Closed by nex3** 2015-03-09 20:50 UTC
